#!/usr/bin/env bash
# Regenerate ~/.claude/skills/toolkit-scout/SKILL.md from ~/.claude/registry.json
# Runs automatically after build-registry.sh, or standalone.
set -euo pipefail

REGISTRY="${HOME}/.claude/registry.json"
OUT="${HOME}/.claude/skills/toolkit-scout/SKILL.md"

if [ ! -f "$REGISTRY" ]; then
  echo "toolkit-scout: registry not found at $REGISTRY — run build-registry.sh first" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

python3 - "$REGISTRY" "$OUT" <<'PYEOF'
import json, sys, re
from collections import Counter, defaultdict
from pathlib import Path

reg = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
out = Path(sys.argv[2])

items = reg.get("items", [])
by_kind = defaultdict(list)
for it in items:
    by_kind[it["kind"]].append(it)

def prefix_of(name: str) -> str:
    # Plugin pack: "pack:skill" -> "pack:"
    if ":" in name:
        return name.split(":", 1)[0] + ":"
    # Hyphen family — for big flood families, go 2 segments deep so
    # saraev-biz-* / saraev-cc-* / saraev-outbound-* are separate rows
    # instead of collapsing 500+ skills into one unnavigable "saraev-*" bucket.
    DEEP_FAMILIES = {"saraev", "ariz", "tob", "hassid", "linkdrop", "mundi", "gstack", "rodman"}
    parts = name.split("-")
    if len(parts) >= 2 and len(parts[0]) >= 2:
        first = parts[0]
        if first in DEEP_FAMILIES and len(parts) >= 3:
            return f"{first}-{parts[1]}-*"
        return first + "-*"
    return name  # standalone

def family_table(kind, top_n=30, min_count=3):
    c = Counter(prefix_of(it["name"]) for it in by_kind.get(kind, []))
    rows = sorted(c.items(), key=lambda x: (-x[1], x[0]))
    big = [(k, v) for k, v in rows if v >= min_count]
    small = [(k, v) for k, v in rows if v < min_count]
    lines = []
    for k, v in big[:top_n]:
        lines.append(f"| `{k}` | {v} |")
    if small:
        lines.append(f"| (other standalone) | {len(small)} |")
    return lines

def command_namespaces():
    c = Counter()
    for it in by_kind.get("command", []):
        n = it["name"].lstrip("/")
        ns = n.split(":", 1)[0] if ":" in n else "(root)"
        c[ns] += 1
    return sorted(c.items(), key=lambda x: (-x[1], x[0]))

def mcp_list():
    return sorted(it["name"] for it in by_kind.get("mcp", []))

lines = []
lines.append("---")
lines.append("name: toolkit-scout")
desc = (
    f"Auto-generated inventory ({reg.get('item_count', 0)} items; "
    f"{len(by_kind.get('skill', []))} skills, "
    f"{len(by_kind.get('agent', []))} agents, "
    f"{len(by_kind.get('command', []))} commands, "
    f"{len(by_kind.get('mcp', []))} MCPs, "
    f"{len(by_kind.get('script', []))} scripts). "
    "Regenerated by ~/.claude/scripts/build-toolkit-scout.sh. "
    "For lookups use router-hub: `bash ~/.claude/scripts/route.sh \"<task>\" --top=5`."
)
lines.append(f"description: {desc}")
lines.append("---")
lines.append("")
lines.append("# Toolkit Scout (auto-generated)")
lines.append("")
lines.append(f"**Registry built:** `{reg.get('generated_at', 'unknown')}`  ")
lines.append(f"**Total items:** {reg.get('item_count', 0)}  ")
lines.append(f"**Source:** `~/.claude/registry.json`  ")
lines.append("**Regenerate:** `bash ~/.claude/scripts/build-toolkit-scout.sh`")
lines.append("")
lines.append("## Counts by kind")
lines.append("")
lines.append("| Kind | Count |")
lines.append("|------|-------|")
for k in sorted(by_kind.keys()):
    lines.append(f"| {k} | {len(by_kind[k])} |")
lines.append("")

lines.append("## Skill families (by slug prefix)")
lines.append("")
lines.append("| Family | Count |")
lines.append("|--------|-------|")
lines.extend(family_table("skill", top_n=40, min_count=3))
lines.append("")
lines.append("_Full skill list lives in `~/.claude/registry.json` under `items[].name` where `kind=='skill'`._")
lines.append("")

lines.append("## Agent families")
lines.append("")
lines.append("| Family | Count |")
lines.append("|--------|-------|")
lines.extend(family_table("agent", top_n=30, min_count=2))
lines.append("")

lines.append("## Command namespaces")
lines.append("")
lines.append("| Namespace | Count |")
lines.append("|-----------|-------|")
for ns, n in command_namespaces()[:40]:
    lines.append(f"| `/{ns}:*`" + (" (root slash-commands)" if ns == "(root)" else "") + f" | {n} |")
lines.append("")

lines.append("## MCP servers")
lines.append("")
for m in mcp_list():
    lines.append(f"- `{m}`")
lines.append("")

lines.append("## How to use")
lines.append("")
lines.append("- **Find by task:** `bash ~/.claude/scripts/route.sh \"<task>\" --top=5`")
lines.append("- **Find by kind:** `bash ~/.claude/scripts/route.sh \"<task>\" --kind=skill --top=10`")
lines.append("- **Inspect full metadata:** read `~/.claude/registry.json`")
lines.append("- **Invoke a skill:** `Skill({skill: '<name>'})` or `/<command>`")
lines.append("- **Dispatch an agent:** `Task(subagent_type='<agent-name>', ...)`")
lines.append("")
lines.append("## Drift prevention")
lines.append("")
lines.append("This file is auto-generated. Do not edit by hand — edits will be overwritten next registry rebuild.")
lines.append("")
lines.append("`build-registry.sh` invokes this script at the end so the two stay in sync.")
lines.append("")

out.write_text("\n".join(lines), encoding="utf-8")
print(f"[toolkit-scout] wrote {out} ({len(lines)} lines, {reg.get('item_count', 0)} items)")
PYEOF
